/**
 * AquaERP Storefront Theme Registry — 14 globally-compliant presets.
 * WCAG 2.2 AA minimum (nordic-clean targets AAA on body text).
 */

export type HeroStyle = 'full-bleed' | 'split' | 'minimal' | 'video-overlay'
export type ProductGridCols = 2 | 3 | 4
export type CardStyle = 'elevated' | 'bordered' | 'flat' | 'organic'

export interface StorefrontThemeTokens {
  primary: string
  primaryForeground: string
  secondary: string
  accent: string
  background: string
  surface: string
  surfaceAlt: string
  text: string
  textMuted: string
  border: string
  success: string
  warning: string
  fontHeading: string
  fontBody: string
  radius: string
  shadow: string
  heroStyle: HeroStyle
  productGridCols: ProductGridCols
  cardStyle: CardStyle
}

export interface StorefrontTheme {
  id: string
  name: string
  description: string
  category: 'retail' | 'premium' | 'dark' | 'regional' | 'b2b' | 'specialty'
  previewGradient: string
  standards: string[]
  wcagLevel: 'AA' | 'AAA'
  tokens: StorefrontThemeTokens
}

export const STOREFRONT_THEMES: StorefrontTheme[] = [
  {
    id: 'ocean-classic',
    name: 'Ocean Classic',
    description: 'Clean Shopify-inspired layout. Trust-building blue palette for general seafood retail.',
    category: 'retail',
    previewGradient: 'linear-gradient(135deg, #0ea5e9 0%, #0369a1 100%)',
    standards: ['WCAG 2.2 AA', 'Schema.org Product', 'Mobile-first', 'GDPR cookie slot'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#0ea5e9',
      primaryForeground: '#ffffff',
      secondary: '#0284c7',
      accent: '#06b6d4',
      background: '#f8fafc',
      surface: '#ffffff',
      surfaceAlt: '#f1f5f9',
      text: '#0f172a',
      textMuted: '#64748b',
      border: '#e2e8f0',
      success: '#10b981',
      warning: '#f59e0b',
      fontHeading: 'var(--font-geist-sans), system-ui, sans-serif',
      fontBody: 'var(--font-geist-sans), system-ui, sans-serif',
      radius: '0.5rem',
      shadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
      heroStyle: 'full-bleed',
      productGridCols: 3,
      cardStyle: 'elevated',
    },
  },
  {
    id: 'coastal-minimal',
    name: 'Coastal Minimal',
    description: 'Editorial serif headlines, generous whitespace. Ideal for premium fillets and sashimi-grade.',
    category: 'premium',
    previewGradient: 'linear-gradient(135deg, #fafaf9 0%, #d6d3d1 100%)',
    standards: ['WCAG 2.2 AA', 'High readability', 'EU consumer clarity'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#1c1917',
      primaryForeground: '#fafaf9',
      secondary: '#57534e',
      accent: '#78716c',
      background: '#fafaf9',
      surface: '#ffffff',
      surfaceAlt: '#f5f5f4',
      text: '#1c1917',
      textMuted: '#78716c',
      border: '#e7e5e4',
      success: '#059669',
      warning: '#d97706',
      fontHeading: 'Georgia, "Times New Roman", serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.25rem',
      shadow: '0 1px 3px rgb(0 0 0 / 0.08)',
      heroStyle: 'minimal',
      productGridCols: 2,
      cardStyle: 'flat',
    },
  },
  {
    id: 'market-fresh',
    name: 'Market Fresh',
    description: 'Wet-market energy with fresh green accents. Same-day catch positioning.',
    category: 'retail',
    previewGradient: 'linear-gradient(135deg, #22c55e 0%, #15803d 100%)',
    standards: ['WCAG 2.2 AA', 'Per-kg pricing', 'Traceability badge'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#16a34a',
      primaryForeground: '#ffffff',
      secondary: '#15803d',
      accent: '#84cc16',
      background: '#f0fdf4',
      surface: '#ffffff',
      surfaceAlt: '#dcfce7',
      text: '#14532d',
      textMuted: '#4b5563',
      border: '#bbf7d0',
      success: '#22c55e',
      warning: '#eab308',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.75rem',
      shadow: '0 4px 14px rgb(22 163 74 / 0.15)',
      heroStyle: 'split',
      productGridCols: 3,
      cardStyle: 'bordered',
    },
  },
  {
    id: 'premium-export',
    name: 'Premium Export',
    description: 'Luxury dark canvas with gold accents. Export-grade tuna, lobster, and caviar.',
    category: 'premium',
    previewGradient: 'linear-gradient(135deg, #1a1a2e 0%, #c9a227 100%)',
    standards: ['WCAG 2.2 AA', 'HS code display', 'Export docs link'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#c9a227',
      primaryForeground: '#0f0f14',
      secondary: '#8b7355',
      accent: '#e8d5a3',
      background: '#0f0f14',
      surface: '#1a1a24',
      surfaceAlt: '#252532',
      text: '#f5f5f4',
      textMuted: '#a8a29e',
      border: '#3f3f50',
      success: '#34d399',
      warning: '#fbbf24',
      fontHeading: '"Playfair Display", Georgia, serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.125rem',
      shadow: '0 8px 32px rgb(0 0 0 / 0.4)',
      heroStyle: 'video-overlay',
      productGridCols: 2,
      cardStyle: 'bordered',
    },
  },
  {
    id: 'harbor-dark',
    name: 'Harbor Dark',
    description: 'Modern dark mode for night markets and urban delivery brands.',
    category: 'dark',
    previewGradient: 'linear-gradient(135deg, #0f172a 0%, #334155 100%)',
    standards: ['WCAG 2.2 AA dark', 'Reduced eye strain', 'prefers-color-scheme'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#38bdf8',
      primaryForeground: '#0f172a',
      secondary: '#64748b',
      accent: '#22d3ee',
      background: '#0f172a',
      surface: '#1e293b',
      surfaceAlt: '#334155',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      border: '#475569',
      success: '#4ade80',
      warning: '#facc15',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.5rem',
      shadow: '0 4px 20px rgb(0 0 0 / 0.5)',
      heroStyle: 'full-bleed',
      productGridCols: 3,
      cardStyle: 'elevated',
    },
  },
  {
    id: 'swahili-coast',
    name: 'Swahili Coast',
    description: 'Warm terracotta and ocean teal. African coastal identity (Kenya, Tanzania, Mozambique).',
    category: 'regional',
    previewGradient: 'linear-gradient(135deg, #c2410c 0%, #0d9488 100%)',
    standards: ['WCAG 2.2 AA', 'M-Pesa ready', 'Swahili/English header slot'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#c2410c',
      primaryForeground: '#fff7ed',
      secondary: '#0d9488',
      accent: '#f59e0b',
      background: '#fff7ed',
      surface: '#ffffff',
      surfaceAlt: '#ffedd5',
      text: '#431407',
      textMuted: '#78716c',
      border: '#fed7aa',
      success: '#059669',
      warning: '#d97706',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.625rem',
      shadow: '0 4px 12px rgb(194 65 12 / 0.12)',
      heroStyle: 'split',
      productGridCols: 3,
      cardStyle: 'organic',
    },
  },
  {
    id: 'ice-cold',
    name: 'Ice & Cold',
    description: 'Frozen-chain emphasis with ice blues. Blast-frozen and cold-storage products.',
    category: 'specialty',
    previewGradient: 'linear-gradient(135deg, #e0f2fe 0%, #7dd3fc 100%)',
    standards: ['WCAG 2.2 AA', 'Cold-chain badge', 'Shelf-life prominent'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#0284c7',
      primaryForeground: '#ffffff',
      secondary: '#0c4a6e',
      accent: '#38bdf8',
      background: '#f0f9ff',
      surface: '#ffffff',
      surfaceAlt: '#e0f2fe',
      text: '#0c4a6e',
      textMuted: '#64748b',
      border: '#bae6fd',
      success: '#0ea5e9',
      warning: '#f59e0b',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.375rem',
      shadow: '0 2px 8px rgb(2 132 199 / 0.12)',
      heroStyle: 'minimal',
      productGridCols: 4,
      cardStyle: 'bordered',
    },
  },
  {
    id: 'auction-live',
    name: 'Auction Live',
    description: 'Bold typography and urgency cues for live fish auctions and daily landings.',
    category: 'specialty',
    previewGradient: 'linear-gradient(135deg, #dc2626 0%, #1f2937 100%)',
    standards: ['WCAG 2.2 AA', 'Countdown/timer slot', 'Real-time price'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#dc2626',
      primaryForeground: '#ffffff',
      secondary: '#1f2937',
      accent: '#fbbf24',
      background: '#ffffff',
      surface: '#f9fafb',
      surfaceAlt: '#fef2f2',
      text: '#111827',
      textMuted: '#6b7280',
      border: '#e5e7eb',
      success: '#16a34a',
      warning: '#ea580c',
      fontHeading: 'system-ui, Impact, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.25rem',
      shadow: '0 6px 16px rgb(220 38 38 / 0.2)',
      heroStyle: 'full-bleed',
      productGridCols: 2,
      cardStyle: 'bordered',
    },
  },
  {
    id: 'cooperative',
    name: 'Cooperative',
    description: 'Friendly rounded UI for BMU and fisherman cooperatives. Community-first.',
    category: 'regional',
    previewGradient: 'linear-gradient(135deg, #7c3aed 0%, #a78bfa 100%)',
    standards: ['WCAG 2.2 AA', 'Member stories slot', 'Fair trade badge'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#7c3aed',
      primaryForeground: '#ffffff',
      secondary: '#5b21b6',
      accent: '#a78bfa',
      background: '#faf5ff',
      surface: '#ffffff',
      surfaceAlt: '#f3e8ff',
      text: '#3b0764',
      textMuted: '#6b7280',
      border: '#e9d5ff',
      success: '#10b981',
      warning: '#f59e0b',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '1rem',
      shadow: '0 4px 14px rgb(124 58 237 / 0.15)',
      heroStyle: 'split',
      productGridCols: 3,
      cardStyle: 'organic',
    },
  },
  {
    id: 'wholesale-b2b',
    name: 'Wholesale B2B',
    description: 'Dense product grid, corporate navy. Restaurants, hotels, and distributors.',
    category: 'b2b',
    previewGradient: 'linear-gradient(135deg, #1e3a5f 0%, #3b82f6 100%)',
    standards: ['WCAG 2.2 AA', 'MOQ display', 'Quick reorder', 'VAT excl. toggle'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#1e40af',
      primaryForeground: '#ffffff',
      secondary: '#1e3a8a',
      accent: '#3b82f6',
      background: '#f8fafc',
      surface: '#ffffff',
      surfaceAlt: '#eff6ff',
      text: '#0f172a',
      textMuted: '#475569',
      border: '#cbd5e1',
      success: '#059669',
      warning: '#d97706',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.25rem',
      shadow: 'none',
      heroStyle: 'minimal',
      productGridCols: 4,
      cardStyle: 'flat',
    },
  },
  {
    id: 'tropical-vibrant',
    name: 'Tropical Vibrant',
    description: 'High-energy coral and teal for beach resorts and tourism seafood.',
    category: 'retail',
    previewGradient: 'linear-gradient(135deg, #f97316 0%, #14b8a6 100%)',
    standards: ['WCAG 2.2 AA', 'Tourism-friendly', 'Multi-lang header'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#f97316',
      primaryForeground: '#ffffff',
      secondary: '#14b8a6',
      accent: '#ec4899',
      background: '#fffbeb',
      surface: '#ffffff',
      surfaceAlt: '#fef3c7',
      text: '#1f2937',
      textMuted: '#6b7280',
      border: '#fde68a',
      success: '#10b981',
      warning: '#ef4444',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '1rem',
      shadow: '0 8px 24px rgb(249 115 22 / 0.2)',
      heroStyle: 'full-bleed',
      productGridCols: 3,
      cardStyle: 'elevated',
    },
  },
  {
    id: 'nordic-clean',
    name: 'Nordic Clean',
    description: 'Scandinavian minimalism with AAA body contrast. EU Nordic export buyers.',
    category: 'premium',
    previewGradient: 'linear-gradient(135deg, #ffffff 0%, #111827 100%)',
    standards: ['WCAG 2.2 AAA', 'EU labeling', 'Sustainability focus'],
    wcagLevel: 'AAA',
    tokens: {
      primary: '#111827',
      primaryForeground: '#ffffff',
      secondary: '#374151',
      accent: '#6b7280',
      background: '#ffffff',
      surface: '#ffffff',
      surfaceAlt: '#f9fafb',
      text: '#111827',
      textMuted: '#4b5563',
      border: '#d1d5db',
      success: '#047857',
      warning: '#b45309',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0',
      shadow: 'none',
      heroStyle: 'minimal',
      productGridCols: 2,
      cardStyle: 'flat',
    },
  },
  {
    id: 'artisan-local',
    name: 'Artisan Local',
    description: 'Handcrafted smokehouse and artisan processor aesthetic. Organic card shapes.',
    category: 'specialty',
    previewGradient: 'linear-gradient(135deg, #d4a574 0%, #8b6914 100%)',
    standards: ['WCAG 2.2 AA', 'Story/origin block', 'Small-batch badge'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#92400e',
      primaryForeground: '#fffbeb',
      secondary: '#78350f',
      accent: '#d97706',
      background: '#fffbeb',
      surface: '#ffffff',
      surfaceAlt: '#fef3c7',
      text: '#451a03',
      textMuted: '#78716c',
      border: '#fde68a',
      success: '#65a30d',
      warning: '#ca8a04',
      fontHeading: 'Georgia, serif',
      fontBody: 'system-ui, sans-serif',
      radius: '1.25rem',
      shadow: '0 4px 12px rgb(146 64 14 / 0.1)',
      heroStyle: 'split',
      productGridCols: 2,
      cardStyle: 'organic',
    },
  },
  {
    id: 'global-trade',
    name: 'Global Trade',
    description: 'Neutral corporate storefront for international seafood trade desks.',
    category: 'b2b',
    previewGradient: 'linear-gradient(135deg, #334155 0%, #94a3b8 100%)',
    standards: ['WCAG 2.2 AA', 'HS code', 'Incoterms footer', 'Multi-currency'],
    wcagLevel: 'AA',
    tokens: {
      primary: '#334155',
      primaryForeground: '#ffffff',
      secondary: '#475569',
      accent: '#0ea5e9',
      background: '#f1f5f9',
      surface: '#ffffff',
      surfaceAlt: '#e2e8f0',
      text: '#0f172a',
      textMuted: '#64748b',
      border: '#cbd5e1',
      success: '#059669',
      warning: '#d97706',
      fontHeading: 'system-ui, sans-serif',
      fontBody: 'system-ui, sans-serif',
      radius: '0.375rem',
      shadow: '0 1px 4px rgb(0 0 0 / 0.06)',
      heroStyle: 'minimal',
      productGridCols: 4,
      cardStyle: 'bordered',
    },
  },
]

export function getStorefrontTheme(id: string): StorefrontTheme | undefined {
  return STOREFRONT_THEMES.find((t) => t.id === id)
}

export function themeToCssVars(tokens: StorefrontThemeTokens): Record<string, string> {
  return {
    '--sf-primary': tokens.primary,
    '--sf-primary-fg': tokens.primaryForeground,
    '--sf-secondary': tokens.secondary,
    '--sf-accent': tokens.accent,
    '--sf-bg': tokens.background,
    '--sf-surface': tokens.surface,
    '--sf-surface-alt': tokens.surfaceAlt,
    '--sf-text': tokens.text,
    '--sf-text-muted': tokens.textMuted,
    '--sf-border': tokens.border,
    '--sf-success': tokens.success,
    '--sf-warning': tokens.warning,
    '--sf-font-heading': tokens.fontHeading,
    '--sf-font-body': tokens.fontBody,
    '--sf-radius': tokens.radius,
    '--sf-shadow': tokens.shadow,
  }
}
